export const mockPosts = [
  {
    id: 1,
    title: 'Getting Started with Next.js 14',
    excerpt: 'Learn how to build modern web applications using Next.js 14 with the new App Router and server components...',
    status: 'published',
    category: 'Technology',
    author: 'John Doe',
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
    tags: ['nextjs', 'react', 'web'],
    views: 1250,
    comments: 24,
    readTime: '5 min',
    featured: false,
    pinned: false
  },
  {
    id: 2,
    title: 'Mastering Tailwind CSS',
    excerpt: 'Advanced techniques and best practices for using Tailwind CSS in your projects...',
    status: 'published',
    category: 'Web Design',
    author: 'Jane Smith',
    createdAt: '2024-01-14',
    updatedAt: '2024-01-14',
    tags: ['tailwind', 'css', 'design'],
    views: 890,
    comments: 18,
    readTime: '8 min',
    featured: false,
    pinned: true
  },
  {
    id: 3,
    title: 'The Future of Web Development',
    excerpt: 'Exploring upcoming trends and technologies in web development...',
    status: 'draft',
    category: 'Technology',
    author: 'Alex Johnson',
    createdAt: '2024-01-13',
    updatedAt: '2024-01-13',
    tags: ['future', 'trends', 'ai'],
    views: 0,
    comments: 0,
    readTime: '10 min',
    featured: false,
    pinned: false
  },
  {
    id: 4,
    title: 'Building Accessible Web Applications',
    excerpt: 'A comprehensive guide to creating web applications that are accessible to everyone...',
    status: 'published',
    category: 'Accessibility',
    author: 'Sam Wilson',
    createdAt: '2024-01-12',
    updatedAt: '2024-01-12',
    tags: ['accessibility', 'a11y', 'web'],
    views: 650,
    comments: 12,
    readTime: '12 min',
    featured: false,
    pinned: false
  },
  {
    id: 5,
    title: 'React Hooks Deep Dive',
    excerpt: 'Understanding React Hooks and how to use them effectively in your applications...',
    status: 'published',
    category: 'Technology',
    author: 'John Doe',
    createdAt: '2024-01-11',
    updatedAt: '2024-01-11',
    tags: ['react', 'hooks', 'javascript'],
    views: 2100,
    comments: 42,
    readTime: '15 min',
    featured: false,
    pinned: false
  },
  {
    id: 6,
    title: 'TypeScript for React Developers',
    excerpt: 'Learn how to use TypeScript effectively with React for better type safety...',
    status: 'published',
    category: 'Technology',
    author: 'Jane Smith',
    createdAt: '2024-01-10',
    updatedAt: '2024-01-10',
    tags: ['typescript', 'react', 'web'],
    views: 1800,
    comments: 31,
    readTime: '20 min',
    featured: false,
    pinned: false
  },
  {
    id: 7,
    title: 'Building REST APIs with Node.js',
    excerpt: 'A complete guide to building RESTful APIs using Node.js and Express...',
    status: 'draft',
    category: 'Backend',
    author: 'Alex Johnson',
    createdAt: '2024-01-09',
    updatedAt: '2024-01-09',
    tags: ['nodejs', 'api', 'backend'],
    views: 0,
    comments: 0,
    readTime: '25 min',
    featured: false,
    pinned: false
  },
  {
    id: 8,
    title: 'Database Design Best Practices',
    excerpt: 'Learn the best practices for designing scalable and efficient databases...',
    status: 'published',
    category: 'Database',
    author: 'Sam Wilson',
    createdAt: '2024-01-08',
    updatedAt: '2024-01-08',
    tags: ['database', 'sql', 'design'],
    views: 950,
    comments: 15,
    readTime: '18 min',
    featured: false,
    pinned: false
  },
  {
    id: 9,
    title: 'Web Performance Optimization',
    excerpt: 'Techniques and tools to optimize your website for better performance...',
    status: 'published',
    category: 'Performance',
    author: 'John Doe',
    createdAt: '2024-01-07',
    updatedAt: '2024-01-07',
    tags: ['performance', 'web', 'optimization'],
    views: 1100,
    comments: 22,
    readTime: '14 min',
    featured: false,
    pinned: true
  },
  {
    id: 10,
    title: 'Mobile First Design Approach',
    excerpt: 'Learn why mobile-first design is important and how to implement it...',
    status: 'published',
    category: 'Web Design',
    author: 'Jane Smith',
    createdAt: '2024-01-06',
    updatedAt: '2024-01-06',
    tags: ['mobile', 'design', 'responsive'],
    views: 780,
    comments: 19,
    readTime: '9 min',
    featured: false,
    pinned: false
  },
]